name: Run Paradise Poster Generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  # please change to your own config.
  # this actions generate only this year
  # If you fork this please change the type to yours below
  TYPE: "github, wakatime, leetcode"
  ME: Paradise
  GITHUB_NAME: xiumu2017
  GITHUB_EMAIL: zdparadise@icloud.com

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      # from pdm
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip3 install -U github_poster
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync github script
        if: contains(env.TYPE, 'github')
        run: |
          github_poster github --github_user_name ${{ secrets.G_USER_NAME }} --me ${{ env.ME }}

#       - name: Run sync wakatime script
#         if: contains(env.TYPE, 'wakatime')
#         run: |
#          github_poster wakatime --wakatime_key "${{ secrets.WAKATIME_KEY }}" --me ${{ env.ME }}

      - name: Mv svg files to examples
        # only for me to show
        if: github.repository_owner == 'xiumu2017'
        run: mv OUT_FOLDER/*.svg examples/

      - name: Push new svg posters
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'update new poster' || echo "nothing to commit"
          git push || echo "nothing to push"
#         uses: github-actions-x/commit@v2.6
#         with:
#           github-token: ${{ secrets.G_T }}
#           commit-message: "Make new poster everyday"
#           files: examples
#           rebase: "true"
#           name: ${{ env.GITHUB_NAME }}
#           email: ${{ env.GITHUB_EMAIL }}
