name: Run Paradise Poster Generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  # please change to your own config.
  # this actions generate only this year
  # If you fork this please change the type to yours below
  TYPE: "github, wakatime, leetcode"
  ME: Paradise
  GITHUB_NAME: xiumu2017
  GITHUB_EMAIL: zdparadise@icloud.com

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      # from pdm
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

#       - name: Run sync duolingo script
#         if: contains(env.TYPE, 'duolingo')
#         run: |
#           python -m github_poster duolingo --duolingo_user_name ${{ secrets.DUOLINGO_USER_NAME }} --duolingo_password ${{ secrets.DUOLINGO_PASSWORD }} --me ${{ env.ME }}

      - name: Run sync leetcode script
        if: contains(env.TYPE, 'leetcode')
        run: |
          python -m github_poster leetcode --leetcode_cookie  '${{ secrets.LEETCODE_COOKIE }}' --me ${{ env.ME }}

#       - name: Run sync twitter script
#         if: contains(env.TYPE, 'twitter')
#         run: |
#           python -m github_poster twitter --twitter_user_name ${{ secrets.TWITTER_USER_NAME }} --me ${{ env.ME }} --with-animation --with-skyline

      - name: Run sync github script
        if: contains(env.TYPE, 'github')
        run: |
          python -m github_poster github --github_user_name ${{ secrets.G_USER_NAME }} --me ${{ env.ME }}

#       - name: Run sync bilibili script
#         if: contains(env.TYPE, 'bilibili')
#         run: |
#           python3 -m github_poster bilibili --bilibili_cookie "${{ secrets.BILIBILI_COOKIE }}" --me ${{ env.ME }}

      - name: Run sync wakatime script
        if: contains(env.TYPE, 'wakatime')
        run: |
          python3 -m github_poster wakatime --wakatime_key "${{ secrets.WAKATIME_KEY }}" --me ${{ env.ME }}

      - name: Mv svg files to examples
        # only for me to show
        if: github.repository_owner == 'xiumu2017'
        run: mv OUT_FOLDER/*.svg examples/

      - name: Push new svg posters
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_T }}
          commit-message: "Make new poster everyday"
          files: examples
          rebase: "true"
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}
